config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('', include('vendors.urls', namespace="vendors")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('route', views.RouteView.as_view(), name="route"),
    path('map', views.MapView.as_view(), name="map"),
]

vendors/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views


app_name = "vendors"

urlpatterns = [
	path('', views.AccountView.as_view(), name="account"),
	path('profile', views.profile_view, name="profile"),
  path('edit_profile', views.edit_profile, name="edit_profile"),
  path('profile_picture_update', views.profile_picture_update, name="profile_picture_update"),
  #Authentication routes
	path('sign_up', views.SignUpView.as_view(), name="sign_up"),
	path('sign_in', views.SignInView.as_view(), name="sign_in"),
	path('sign_out', views.sign_out, name="sign_out"),
  # Brew routes
  url(r'^brews/$', views.brew_list, name='brew_list'),
  url(r'^brews/create/$', views.brew_create, name='brew_create'),
  url(r'^brews/(?P<pk>\d+)/update/$', views.brew_update, name='brew_update'),
  url(r'^brews/(?P<pk>\d+)/delete/$', views.brew_delete, name='brew_delete'),
	]

templates/partials/logo.html
{% load static %}
<a href="{% url 'vendors:account' %}">
	<div class="brand-logo">
		<img class="logo" src="{% static 'images/brewtiful.gif' %}" />
	</div>
</a>

templates/partials/nav.html
{% if request.user.is_authenticated %}
<ul class="sidenav">
  {% if request.path == "/" %}
  <li><a class="active" href="{% url 'vendors:account' %}">Vendor Account</a></li>
  {% else %}
  <li><a href="{% url 'vendors:account' %}">Vendor Account</a></li>
  {% endif %}

  {% if "profile" in request.path %}
  <li><a class="active" href="{% url 'vendors:profile' %}">Vendor Profile</a></li>
  {% else %}
  <li><a href="{% url 'vendors:profile' %}">Vendor Profile</a></li>
  {% endif %}

  {% if "route" in request.path %}
  <li><a class="active" href="{% url 'main:route' %}">Directions</a></li>
  {% else %}
  <li><a href="{% url 'main:route' %}">Directions</a></li>
  {% endif %}

  {% if "map" in request.path %}
  <li><a class="active" href="{% url 'main:map' %}">Map</a></li>
  {% else %}
  <li><a href="{% url 'main:map' %}">Map</a></li>
  {% endif %}

  {% if "sign_out" in request.path %}
  <li><a class="active" href="{% url 'vendors:sign_out' %}">Sign Out</a></li>
  {% else %}
  <li><a href="{% url 'vendors:sign_out' %}">Sign Out</a></li>
  {% endif %}
  
</ul>
{% else %}
<ul class="sidenav">

  {% if "sign_in" in request.path %}
  <li><a class="active" href="{% url 'vendors:sign_in' %}">Sign In</a></li>
  {% else %}
  <li><a href="{% url 'vendors:sign_in' %}">Sign In</a></li>
  {% endif %}
  
  {% if "sign_up" in request.path %}
  <li><a class="active" href="{% url 'vendors:sign_up' %}">Sign Up</a></li>
  {% else %}
  <li><a href="{% url 'vendors:sign_up' %}">Sign Up</a></li>
  {% endif %}
</ul>
{% endif %}