config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('', include('vendors.urls', namespace="vendors")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('route', views.RouteView.as_view(), name="route"),
    path('map', views.MapView.as_view(), name="map"),
]

vendors/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views


app_name = "vendors"

urlpatterns = [
	path('', views.AccountView.as_view(), name="account"),
	path('profile', views.profile_view, name="profile"),
  path('edit_profile', views.edit_profile, name="edit_profile"),
  path('profile_picture_update', views.profile_picture_update, name="profile_picture_update"),
  #Authentication routes
	path('sign_up', views.SignUpView.as_view(), name="sign_up"),
	path('sign_in', views.SignInView.as_view(), name="sign_in"),
	path('sign_out', views.sign_out, name="sign_out"),
  # Brew routes
  url(r'^brews/$', views.brew_list, name='brew_list'),
  url(r'^brews/create/$', views.brew_create, name='brew_create'),
  url(r'^brews/(?P<pk>\d+)/update/$', views.brew_update, name='brew_update'),
  url(r'^brews/(?P<pk>\d+)/delete/$', views.brew_delete, name='brew_delete'),
	]

vendors/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files import File
from PIL import Image
from io import BytesIO
import time

# Create your models here.

class VendorProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="Company Name", max_length=100, null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to='static/images/profile/')
    created_at = models.DateTimeField(auto_now_add=True)
 
    address = models.CharField(verbose_name="Address",max_length=100, null=True, blank=True)
    locality = models.CharField(verbose_name="City",max_length=100, null=True, blank=True)
    state = models.CharField(verbose_name="State",max_length=100, null=True, blank=True)
    postal_code = models.CharField(verbose_name="Zip Code",max_length=8, null=True, blank=True)
    country = models.CharField(verbose_name="Country",max_length=100, null=True, blank=True)
    longitude = models.CharField(verbose_name="Longitude",max_length=50, null=True, blank=True)
    latitude = models.CharField(verbose_name="Latitude",max_length=50, null=True, blank=True)

    captcha_score = models.FloatField(default = 0.0)
    has_profile = models.BooleanField(default = False)
	
    is_active = models.BooleanField(default = True)

    def __str__(self):
	      return self.name
 
    class Meta:
        ordering = ['-created_at']
    
    
class Brew(models.Model):
    ALE = 1
    LAGER = 2
    LAMBIC = 3
    BREW_TYPES = (
        (ALE, 'Ale'),
        (LAGER, 'Lager'),
        (LAMBIC, 'Lambic'),
    )
    name = models.CharField(max_length=100, null=True)
    brew_type = models.PositiveSmallIntegerField(choices=BREW_TYPES, null=True)
    brewery = models.CharField(max_length=30, blank=True, null=True)
    description = models.CharField(max_length=255, null=True)
    price = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    image = models.ImageField(blank=True, null=True, upload_to='static/images/brew/')
    
    def __str__(self):
        return self.name
       
      
class Post(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=500)
    vendorprofile = models.ForeignKey(VendorProfile, related_name='post', on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True, upload_to='post/')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_at']
        

vendors/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from .models import VendorProfile, Brew



class UserForm(UserCreationForm):

	first_name = forms.CharField(max_length=30, required=True,
		widget=forms.TextInput(attrs={'placeholder': 'Name of Company...'}))
	last_name = forms.CharField(max_length=30, required=False,
		widget=forms.TextInput(attrs={'placeholder': 'Additional information... (ex. "Slogan")'}))
	username = forms.EmailField(max_length=254, required=True,
		widget=forms.TextInput(attrs={'placeholder': 'Email..', 'autocomplete': 'username'}))
	password1 = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': 'Password..','class':'password', 'autocomplete': 'current-password'}))
	password2 = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password..','class':'password', 'autocomplete': 'current-password'}))

	#reCAPTCHA token
	token = forms.CharField(
		widget=forms.HiddenInput())

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'password1', 'password2', )


class AuthForm(AuthenticationForm):

	username = forms.EmailField(max_length=254, required=True,
		widget=forms.TextInput(attrs={'placeholder': 'Email..', 'autocomplete': 'username'}))
	password = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': 'Password..','class':'password', 'autocomplete': 'current-password'}))

	class Meta:
		model = User
		fields = ('username','password', )


class UserProfileForm(forms.ModelForm):

	address = forms.CharField(max_length=100, required=True, widget = forms.HiddenInput())
	locality = forms.CharField(max_length=100, required=True, widget = forms.HiddenInput())
	state = forms.CharField(max_length=100, required=True, widget = forms.HiddenInput())
	postal_code = forms.CharField(max_length=8, required=True, widget = forms.HiddenInput())
	country = forms.CharField(max_length=40, required=True, widget = forms.HiddenInput())
	longitude = forms.CharField(max_length=50, required=True, widget = forms.HiddenInput())
	latitude = forms.CharField(max_length=50, required=True, widget = forms.HiddenInput())

	class Meta:
		model = VendorProfile
		fields = ('address', 'locality', 'state', 'postal_code',
		 'country', 'longitude', 'latitude')


class EditProfileForm(forms.ModelForm):
  
		class Meta:
				model = VendorProfile
				fields = ('name',)


class ProfileImageForm(ModelForm):

    class Meta:
        model = VendorProfile
        fields = ('image',)


class BrewForm(forms.ModelForm):
    class Meta:
        model = Brew
        fields = ('image', 'name', 'brew_type', 'brewery', 'description', 'price', )
      
        
# class CreatePostForm(ModelForm):
#     title = forms.CharField(max_length=100, required=True, label="", widget=forms.TextInput(attrs={'placeholder': 'Brew Name', 'class': 'modal-form-input',}))
#     description = forms.CharField(max_length=500, required=True, label="", widget=forms.TextInput(attrs={'placeholder': 'Description: Brew Type (ex. Ale, Lager, Lambic) from what Brewery', 'class': 'modal-form-input',}))
    
#     class Meta:
#         model: Post
#         fields = ('title', 'description', 'image')        

vendors/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.conf import settings
from django.http import JsonResponse
from django.views.generic import View
from django.views.generic.edit import FormView, UpdateView
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator
from django.template.loader import render_to_string
from .models import VendorProfile, Brew

from config.mixins import(
	AjaxFormMixin, 
	reCAPTCHAValidation,
	FormErrors,
	RedirectParams,
	)

from .forms import (
	UserForm,
	UserProfileForm,
	AuthForm,
  EditProfileForm,
  ProfileImageForm,
  BrewForm,
	)

result = "Error"
message = "There was an error, please try again"


class AccountView(TemplateView):

	template_name = "vendors/account.html"

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super().dispatch(*args, **kwargs)


def profile_view(request):

	user = request.user
	up = user.vendorprofile

	form = UserProfileForm(instance = up) 

	if request.is_ajax():
		form = UserProfileForm(data = request.POST, instance = up)
		if form.is_valid():
			obj = form.save()
			obj.has_profile = True
			obj.save()
			result = "Success"
			message = "Your profile has been updated"
		else:
			message = FormErrors(form)
		data = {'result': result, 'message': message}
		return JsonResponse(data)

	else:

		context = {'form': form}
		context['google_api_key'] = settings.GOOGLE_API_KEY
		context['base_country'] = settings.BASE_COUNTRY

		return render(request, 'vendors/profile.html', context)

# def edit_profile(request):
#     args = {}

#     if request.method == 'POST':
#         form = EditProfileForm(request.POST)
#         form.actual_user = request.user
#         if form.is_valid():
#             obj=form.save()
#             return reverse('edit_profile')
#     else:
#         form = EditProfileForm()

#     args['form'] = form
#     return render(request, 'vendors/edit_profile.html', args)
  
# # #Save
def save_vendorprofile_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            form = VendorProfile.objects.all()
            data['html_profile'] = render_to_string('vendors/profile.html', {
                'form': form
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data) 
  
def edit_profile(request, pk):
    vendorprofile = get_object_or_404(VendorProfile, pk=pk)
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=vendorprofile)
    else:
        form = EditProfileForm(instance=vendorprofile)
    return save_vendorprofile_form(request, form, 'vendors/edit_profile.html')
    
      
def profile_picture_update(request):
    if request.method == 'POST':
       form = ProfileImageForm(request.POST, request.FILES)
       if form.is_valid():
           obj=form.save()
           return JsonResponse({'error': False, 'message': 'Uploaded Successfully'})
       else:
           return JsonResponse({'error': True, 'errors': form.errors})
    else:
        form = ProfileImageForm()
        return render(request, 'vendors/profile_picture_update.html', {'form': form})

class SignUpView(AjaxFormMixin, FormView):

	template_name = "vendors/sign_up.html"
	form_class = UserForm
	success_url = "/"

	#reCAPTURE key required in context
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["recaptcha_site_key"] = settings.RECAPTCHA_SITE_KEY
		return context

	#over write the mixin logic to get, check and save reCAPTURE score
	def form_valid(self, form):
		response = super(AjaxFormMixin, self).form_valid(form)	
		if self.request.is_ajax():
			token = form.cleaned_data.get('token')
			captcha = reCAPTCHAValidation(token)
			if captcha["success"]:
				obj = form.save()
				obj.email = obj.username
				obj.save()
				up = obj.vendorprofile
				up.captcha_score = float(captcha["score"])
				up.save()
				
				login(self.request, obj, backend='django.contrib.auth.backends.ModelBackend')

				#change result & message on success
				result = "Success"
				message = "Thank you for signing up"

				
			data = {'result': result, 'message': message}
			return JsonResponse(data)

		return response




class SignInView(AjaxFormMixin, FormView):

	template_name = "vendors/sign_in.html"
	form_class = AuthForm
	success_url = "/"

	def form_valid(self, form):
		response = super(AjaxFormMixin, self).form_valid(form)	
		if self.request.is_ajax():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			#attempt to authenticate user
			user = authenticate(self.request, username=username, password=password)
			if user is not None:
				login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
				result = "Success"
				message = 'You are now logged in'
			else:
				message = FormErrors(form)
			data = {'result': result, 'message': message}
			return JsonResponse(data)
		return response

# Sign Out View
def sign_out(request):

	logout(request)
	return redirect(reverse('vendors:sign-in'))



# Brew views
def brew_list(request):
    brews = Brew.objects.all()
    return render(request, 'brew_list.html', {'brews': brews})

def save_brew_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            brews = Brew.objects.all()
            data['html_brew_list'] = render_to_string('includes/partial_brew_list.html', {
                'brews': brews
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data) 
  
def brew_create(request):
    data = dict()

    if request.method == 'POST':
        form = BrewForm(request.POST)
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            brews = Brew.objects.all()
            data['html_brew_list'] = render_to_string('includes/partial_brew_list.html', {
                'brews': brews
            })
        else:
            data['form_is_valid'] = False
    else:
        form = BrewForm()

    context = {'form': form}
    data['html_form'] = render_to_string('includes/partial_brew_create.html',
        context,
        request=request
    )
    return JsonResponse(data)
  
  
def brew_update(request, pk):
    brew = get_object_or_404(Brew, pk=pk)
    if request.method == 'POST':
        form = BrewForm(request.POST, instance=brew)
    else:
        form = BrewForm(instance=brew)
    return save_brew_form(request, form, 'includes/partial_brew_update.html')
  
  
def brew_delete(request, pk):
    brew = get_object_or_404(Brew, pk=pk)
    data = dict()
    if request.method == 'POST':
        brew.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        brews = Brew.objects.all()
        data['html_brew_list'] = render_to_string('includes/partial_brew_list.html', {
            'brews': brews
        })
    else:
        context = {'brew': brew}
        data['html_form'] = render_to_string('includes/partial_brew_delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)  

templates/vendors/account.html
{% extends 'base.html' %}
{% load static %}


{% block extend_head %}


{% endblock %}


{% block content %}

<h3>Company Account</h3>

<div class="container">

  <h4>Company Account Details</h4>
  <table>
    <thead>
      <tr>
        <th>Field</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Username</td>
          <td>{{request.user.username}}</td>
      </tr>
      <tr>
        <td>Name</td>
        <td>{{request.user.first_name|title}} {{request.user.last_name|title}}</td>      
      </tr>


      {% if request.user.vendorprofile.has_profile %}

        <tr>
          <td>Address</td>
          <td>
            <address>
              {{request.user.vendorprofile.address}}<br>
              {{request.user.vendorprofile.locality}}<br>
              {{request.user.vendorprofile.state}}<br>
              {{request.user.vendorprofile.postal_code}}<br>
            </address>
          </td>      
        </tr>

      {% else %}
        <tr>
          <td>Company Profile</td>
          <td><a href="{% url 'vendors:profile' %}"> View Profile </a></td>
        </tr>
      {% endif %}
    </tbody>
  </table>



</div>


{% endblock %}


{% block extend_footer %}

{% endblock %}

templates/vendors/brew_list.html
{% extends 'base.html' %}
{% load static %}

{% block javascript %}
  <script src="{% static 'scripts/brews.js' %}"></script>
{% endblock %}

{% block content %}
  <h1 class="page-header">Brew-skies</h1>

  <p>
    <button type="button"
            class="btn btn-primary js-create-brew"
            data-url="{% url 'vendors/brew_create' %}">
      <span class="glyphicon glyphicon-plus"></span>
      New Brews
    </button>
  </p>

  <table class="table" id="brew-table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Type</th>
        <th>Description</th>
        <th>Brewery</th>
        <th>Price</th>
        <th>Image</th>
      </tr>
    </thead>
    <tbody>
    {% include 'includes/partial_brew_list.html' %}
    </tbody>
  </table>

    <div class="modal fade" id="modal-brew">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
{% endblock %}

templates/vendors/edit_profile.html
{% extends 'base.html' %} {% block content %}

<div class="form-body">
  <main class="form-signin">
    <form class="modal-form" method="post">
      
      <h1 class="modal-title h3 mb-3 fw-normal">Update Profile</h1>
<div class="container-head">
  <a href="{% url 'vendors:profile_picture_update' %}">
    {% if request.user.vendorprofile.has_profile %}
    <p class="profile-header-image-container">{{request.user.vendorprofile.image}}</p>
      <label for="id-image">Add/Change Company Logo Image</label>
    {% else %}
    {% endif %}
    </a>


          <p class="profile-image-headers">{{request.user.vendorprofile.image|title}}</p>
            <td> Name: </td>
            <td class="profile-userinfo-headers">{{request.user.vendorprofile.name|title}}</td>   
            </tr><br>
            <p class="profile-userinfo-headers">Joined: <span class="profile-userinfo">{{ request.user.vendorprofile.created_at|date:"M Y" }}</span></p>
            <br><br>
            <a class="profile-edit-button-link" href="{% url 'vendors:edit_profile' %}">
            </a>
            
</div>
      {% csrf_token %} {{ form.as_p }}

      <input type="submit" class="form-button" value="UPDATE" />
    </form>
  </main>
</div>
{% endblock %}

templates/vendors/profile.html
{% extends 'base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block content %}

<h3>Company Profile</h3>


<div class="container-head">
  <a href="{% url 'vendors:profile_picture_update' %}">
    {% if request.user.vendorprofile.has_profile %}
    <p class="profile-header-image-container">{{request.user.vendorprofile.image}}</p>
      <label for="id-image">Add/Change Company Logo Image</label>
    {% else %}
    {% endif %}
    </a>


          <p class="profile-image-headers">{{request.user.vendorprofile.image|title}}</p>
            <td> Name: </td>
            <td class="profile-userinfo-headers">{{request.user.vendorprofile.name|title}}</td>   
            </tr><br>
            <p class="profile-userinfo-headers">Joined: <span class="profile-userinfo">{{ request.user.vendorprofile.created_at|date:"M Y" }}</span></p>
            <br><br>
            <a class="profile-edit-button-link" href="{% url 'vendors:edit_profile' %}">
                <button type="submit" id="head-profile-btn">Edit</button>
            </a>
            
</div> 

<div class="container">
  {% if request.user.vendorprofile.has_profile %}
  <table>
    <thead>
      <tr>
        <th>Field</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Address</td>
        <td>
          <address>
            {{request.user.vendorprofile.address}}<br>
            {{request.user.vendorprofile.locality}}<br>
            {{request.user.vendorprofile.state}}<br>
            {{request.user.vendorprofile.postal_code}}<br>
          </address>
        </td>      
      </tr>
    </tbody>
  </table>
  </br>
  <label for="id-google-address">Change Address</label>
  {% else %}
  <label for="id-google-address">Add Address</label>
  {% endif %}

  <input type="text" placeholder="Begin typing address" id="id-google-address" name="google_address">

  <form id="profileform" method="POST" action="/profile">
    {% csrf_token %}

   <label for="address" class="hidden-el" hidden>Address</label>
   {{form.address}}

   <label for="locality" class="hidden-el" hidden>City</label>
   {{form.locality}}

   <label for="state" class="hidden-el" hidden>State</label>
   {{form.state}}

   <label for="postal_code" class="hidden-el" hidden>Zip Code</label>
   {{form.postal_code}}

   <label for="country" class="hidden-el" hidden>Country</label>
   {{form.country}}

   <label for="post_code" class="hidden-el" hidden>Longitude</label>
   {{form.longitude}}

   <label for="country"  class="hidden-el" hidden>Latitude</label>
   {{form.latitude}}


   <button disabled type="submit" id="profile-btn">Update</button>
 </form>

</div>

{% endblock %}

{% block extend_footer %}

<script type="text/javascript">

  var google_api_key = "{{google_api_key|safe}}";
  var base_country = "{{base_country|safe}}";

</script>

<script src="{% static 'scripts/google_places.js' %}"></script>

{% endblock %}

templates/vendors/profile_picture_update.html
{% extends 'base.html' %}
{% load static %} 

{% block content %}

<div class="form-body">
  <main class="form-image-update" style="max-width: 600px;">
    <form class="modal-form" style="max-width: 600px;" action="" method="post" enctype="multipart/form-data">
      <h1>Update Company Logo/ Image</h1>
      
      {% csrf_token %} {{form.as_p}}

      <input type="submit" class="form-button" value="UPLOAD" />
    </form>
  </main>
</div>
{% endblock %}

templates/vendors/sign_in.html
{% extends 'base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block content %}

<h3>Vendor Sign In</h3>

<div class="container">

  <form id="signinform" method="POST" action="/sign-in">
    {% csrf_token %}
    <label for="username">Username</label>
    {{form.username}}

    <label for="password">Password</label>
    {{form.password}}

    <label class="check-container">Show Passwords
     <input type="checkbox" onclick="showPword()">
     <span class="checkmark"></span>
   </label>

   <button type="submit">Sign in</button>
 </form>

</div>

{% endblock %}


{% block extend_footer %}

{% endblock %}

templates/vendors/sign_up.html
{% extends 'base.html' %}
{% load static %}


{% block extend_head %}

<script src='https://www.google.com/recaptcha/api.js?render={{recaptcha_site_key}}'></script>

{% endblock %}

{% block content %}

<h3>Vendor Sign Up</h3>

<div class="container">


  <form id="signupform" method="POST" action="/sign_up">
    {% csrf_token %}

    
    <label for="first_name">Name of Company</label>
    {{form.first_name}}

    <label for="last_name">Additional Information...</label>
    {{form.last_name}}

    <label for="username">Username</label>
    {{form.username}}

    <label for="password1">Password</label>
    {{form.password1}}

    <label for="password2">Confirm Password</label>
    {{form.password2}}

    {{form.token}}

    <label class="check-container">Show Passwords
     <input type="checkbox" onclick="showPword()">
     <span class="checkmark"></span>
    </label>

    <button type="submit">Sign up</button>

  </form>
</div>


</div>

{% endblock %}

{% block extend_footer %}

<script type="text/javascript">
  // Create a variable that can be used in main.js
  var recaptcha_site_key = '{{recaptcha_site_key|safe}}'
</script>


{% endblock %}